### ISSUE TITLE
Seperate VREnabler

### ISSUE THREAD

**Issue by Bluscream** [TrevTV/DawnVR#14]
Please seperate DawnVREnabler into it's own repo and rename it to VREnabler, it's a universal plugin and if i had found it earlier it would've spared me a a lot of nerves; https://github.com/Bluscream/unity-vr-patcher

Also you might want to add it to the official universal mods list https://github.com/LavaGang/MelonWiki/blob/master/docs/universalmods.md

**Comment by TrevTV** [comment]
It's set up to specifically inject into LiS, if the game is IL2CPP it'll do the universal patch, otherwise it replaces it with a pre-patched file because (if I remember right) the Mono version of the game would crash if I modified the file.
https://github.com/TrevTV/DawnVR/blob/main/DawnVREnabler/Main.cs#L44C47-L44C47

It's also a bit janky and I don't really feel like developing it more right now

**Comment by TrevTV** [comment]
https://github.com/TrevTV/DawnVR/pull/15#issuecomment-1624278763
